### ISSUE TITLE
[Bug report] 构建网页时发生报错导致网页无法正常显示

### ISSUE THREAD

**Issue by AkarinLiu** [vuepress/core#1523]
### Description

```
PS C:\Users\AkarinLiu\Documents\Git\navpages> yarn docs:build
yarn run v1.22.22
$ vuepress build docs
✔ Initializing and preparing data - done in 906ms
✔ Compiling with vite - done in 10.07s
⠙ Rendering 4 pagesError: useClientData() is called without provider.
    at useClientData (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:223:11)
    at useRouteLocale (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:230:28)
    at useLocaleConfig (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:418:23)
    at useCopyCode (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:484:18)
    at Object.setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:555:5)
    at setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:2914:59)
    at callWithErrorHandling (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:82:19)
    at setupStatefulComponent (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6039:25)
    at setupComponent (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6026:36)
    at renderComponentVNode (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:358:15)
Error: useClientData() is called without provider.
    at useClientData (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:223:11)
    at useRouteLocale (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:230:28)
    at useLocaleConfig (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:418:23)
    at useCopyCode (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:484:18)
    at Object.setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:555:5)
    at setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:2914:59)
    at callWithErrorHandling (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:82:19)
    at setupStatefulComponent (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6039:25)
    at setupComponent (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6026:36)
    at renderComponentVNode (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:358:15)
Error: useClientData() is called without provider.
    at useClientData (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:223:11)
    at useRouteLocale (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:230:28)
    at useLocaleConfig (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:418:23)
    at useCopyCode (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:484:18)
    at Object.setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:555:5)
    at setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:2914:59)
    at callWithErrorHandling (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:82:19)
e.cjs.prod.js:6039:25)
    at setupComponent (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6026:36)
    at renderComponentVNode (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:358:15)
Error: useClientData() is called without provider.
    at useClientData (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:223:11)
    at useRouteLocale (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:230:28)
    at useLocaleConfig (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:418:23)
    at useCopyCode (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:484:18)
    at Object.setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:555:5)
    at setup (file:///C:/Users/AkarinLiu/Documents/Git/navpages/docs/.vuepress/.temp/.server/app.C83FB6Nc.mjs:2914:59)
    at callWithErrorHandling (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:82:19)
    at setupStatefulComponent (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6039:25)
    at setupComponent (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6026:36)
    at renderComponentVNode (C:\Users\AkarinLiu\Documents\Git\navpages\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:358:15)
✔ Rendering 4 pages - done in 182ms
success VuePress build completed in 13.30s!
Done in 14.96s.
```

### Reproduction

https://github.com/AkarinLiu/navpages

### Used Package Manager

yarn

### System Info

```shell
PS C:\Users\AkarinLiu\Documents\Git\navpages> npx vuepress info

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
    Memory: 1.65 GB / 5.68 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
    bun: Not Found
  Utilities:
    Git: 2.44.0.
  Browsers:
    Chrome: Not Found
    Edge: Chromium (123.0.2420.65)
  npmPackages:
    @vuepress/bundler-vite: ^2.0.0-rc.7 => 2.0.0-rc.7
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-rc.9
    @vuepress/client:  2.0.0-rc.7 (2.0.0-rc.9)
    @vuepress/core:  2.0.0-rc.9 (2.0.0-rc.7)
    @vuepress/markdown:  2.0.0-rc.9 (2.0.0-rc.7)
    @vuepress/shared:  2.0.0-rc.9 (2.0.0-rc.7)
    @vuepress/utils:  2.0.0-rc.9 (2.0.0-rc.7)
    vue: ^3.4.0 => 3.4.21
    vue-router:  4.3.0
    vuepress: ^2.0.0-rc.7 => 2.0.0-rc.9
```

**Comment by AkarinLiu** [comment]
> Hello @AkarinLiu. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) using a GitHub repository or [v2.vuepress.vuejs.org/new](https://v2.vuepress.vuejs.org/new). Issues marked with will be closed if they have no activity within 7 days.`need reproduction`

https://github.com/AkarinLiu/navpages

**Comment by AkarinLiu** [comment]
https://github.com/AkarinLiu/navpages

**Comment by Mister-Hope** [comment]
Use the same version first

**Comment by Mister-Hope** [comment]
```
    @vuepress/bundler-vite: ^2.0.0-rc.7 => 2.0.0-rc.7
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-rc.9
    @vuepress/client:  2.0.0-rc.7 (2.0.0-rc.9)
    @vuepress/core:  2.0.0-rc.9 (2.0.0-rc.7)
    @vuepress/markdown:  2.0.0-rc.9 (2.0.0-rc.7)
    @vuepress/shared:  2.0.0-rc.9 (2.0.0-rc.7)
    @vuepress/utils:  2.0.0-rc.9 (2.0.0-rc.7)
    vue: ^3.4.0 => 3.4.21
    vue-router:  4.3.0
    vuepress: ^2.0.0-rc.7 => 2.0.0-rc.9
```

Closing as you are not using the same version, and the test passed
